- name: Set up local workstation
  hosts: local
  roles:
    - role: github
      tags:
        -github
    - role: zsh
      tags:
        - zsh
    - role: tmux
      tags:
        - tmux
    - role: nvim
      tags:
        - nvim
