- name: Set up local workstation
  hosts: local
  vars:
    git_username: Ramonnn
    git_email: 29675067+Ramonnn@users.noreply.github.com
    git_defaultbranch: main
    repo: "git@github.com:Ramonnn/lazy-nvim-setup.git"
    dest: "~/.config/nvim/"
  roles:
    - role: github
      tags:
        - github
    - role: zsh
      tags:
        - zsh
    - role: tmux
      tags:
        - tmux
    - role: nvim
      tags:
        - nvim
