- name: Continue setup
  hosts: local
  vars:
    repo: "git@github.com:Ramonnn/lazy-nvim-setup.git"
    dest: "~/.config/nvim/"
  roles:
    - role: zsh
      tags:
        - zsh
    - role: tmux
      tags:
        - tmux
    - role: nvim
      tags:
        - nvim

