- name: Set up local workstation
  hosts: local
  roles:
    - role: git
      tags:
        -git
    - role: zsh
      tags:
        - zsh
    - role: tmux
      tags:
        - tmux
    - role: nvim
      tags:
        - nvim
