- name: Install Git
  become: yes
  become_user: root
  apt:
    name: git
    state: present
    update_cache: yes

- name: Set Git username
  git_config:
    name: user.name
    value: "{{ git_username }}"
    scope: global
  when: git_username is defined

- name: Set Git email
  git_config:
    name: user.email
    value: "{{ git_email }}"
    scope: global
  when: git_email is defined

- name: Set Git default branch
  git_config:
    name: init.defaultBranch
    value: "{{ git_defaultbranch }}"
    scope: global
  when: git_defaultbranch is defined

- name: create ssh folder
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"
