- name: Install Git
  become: yes
  become_user: root
  apt:
    name: git
    state: present
    update_cache: yes

- name: Set Git username
  git_config:
    name: user.name
    value: "{{ git_username }}"
    scope: global
  when: git_username is defined

- name: Set Git email
  git_config:
    name: user.email
    value: "{{ git_email }}"
    scope: global
  when: git_email is defined

- name: Set Git default branch
  git_config:
    name: init.defaultBranch
    value: "{{ git_defaultbranch }}"
    scope: global
  when: git_defaultbranch is defined

- name: check for ssh folder
  become: yes
  become_user: root
  shell: |
    ssh_folder="~/.ssh" 
    if [ ! -d "$ssh_folder" ]; then 
      mkdir -p "$ssh_folder" 
      chmod 700 "$ssh_folder"
      echo "Created ssh folder"
    else
      echo "ssh folder already exists"
    fi
- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: ~/.ssh/github_ssh
    comment: "{{ git_email }}"
    type: "ed25519"
- name: start ssh-agent
  become: yes
  become_user: root
  shell:
    cmd: |
      eval "$(ssh-agent -s)"
      ssh-add ~/.ssh/github_ssh
- name: show public key
  become: yes
  become_user: root
  shell: cat ~/.ssh/github_ssh.pub
- name: pause to add the public key to github
  pause:
    prompt: "Add the public ssh key to github. After that press any key to continue."
