- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Set Git username
  git_config:
    name: user.name
    value: "{{ git_username }}"
    scope: global
  when: git_username is defined

- name: Set Git email
  git_config:
    name: user.email
    value: "{{ git_email }}"
    scope: global
  when: git_email is defined

- name: Set Git default branch
  git_config:
    name: init.defaultBranch
    value: "{{ git_defaultbranch }}"
    scope: global
  when: git_defaultbranch is defined

- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: ~/.ssh/github_ssh
    comment: "{{ git_email }}"
    type: "ed25519"
- name: start ssh-agent
  shell:
    cmd: 'eval "$(ssh-agent -s)"'
- name: check for ssh folder
  become: yes
  become_user: root
  shell:
    cmd: 'sudo ssh_folder="$HOME/.ssh; if [ ! -d "$ssh_folder" ]; then sudo mkdir -p "$ssh_folder"; sudo chmod 700 "$ssh_folder"; fi'
- name: add private ssh key to ssh agent
  become: yes
  become_user: root
  shell:
    cmd: "sudo ssh-add ~/.ssh/github_ssh"
- name: pause to add the public key to github
  pause:
    prompt: "Add the public ssh key to github. After that press any key to continue."
