- name: Install Git
  become: yes
  become_user: root
  apt:
    name: git
    state: present
    update_cache: yes

- name: Set Git username
  git_config:
    name: user.name
    value: "{{ git_username }}"
    scope: global
  when: git_username is defined

- name: Set Git email
  git_config:
    name: user.email
    value: "{{ git_email }}"
    scope: global
  when: git_email is defined

- name: Set Git default branch
  git_config:
    name: init.defaultBranch
    value: "{{ git_defaultbranch }}"
    scope: global
  when: git_defaultbranch is defined

- name: create ssh folder
  become: yes
  become_user: root
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"

- name: start ssh-agent
  become: yes
  become_user: root
  shell:
    cmd: |
      eval "$(command -v ssh-agent) -s"
      export SSH_AUTH_SOCK
      export SSH_AGENT_PID
      ssh-add ~/.ssh/github_ssh

- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: "~/.ssh/github_ssh"
    comment: "{{ git_email }}"
    type: "ed25519"

- name: show public key
  become: yes
  become_user: root
  command: "cat ~/.ssh/github_ssh.pub"
  register: public_key_output

- name: debug promt through on terminal
  debug:
    var: public_key_output.stdout_lines

- name: pause to add the public key to github
  pause:
    prompt: "Add the public ssh key to github. After that press any key to continue."
